### PR TITLE
HH GitHub profiles

### PR DESCRIPTION
**Pull request by zmughal**
Sourced from:
- https://www.facebook.com/groups/hackathonhackers/permalink/952321611489991/
- https://www.facebook.com/groups/hackathonhackers/permalink/810461312342689/
- https://www.facebook.com/groups/hackathonhackers/permalink/914419521946867/
- https://www.facebook.com/groups/hackathonhackers/permalink/931741230214696/

Warning: not everything has been checked for correctness. Only some minimal
sanity checking has been done. Some people have changed their GitHub usernames
in the interim.

### CODE REVIEW

**Comment by zmughal** [comment]
This kind of closes #64. But a table would be nice.

**Comment by bryangarza** [comment]
nice

**Comment by iangcarroll** [comment]
Wouldn't this be better suited for a separate file?

**Comment by zmughal** [comment]
Up to you. I just wanted the data... for reasons... uh, for **science**. :microscope:

I was originally going to put everything in YAML so that it is easily machine-readable.

**Pull request merged**
